name: nx-workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

# Needed for nx-set-shas within nx-cloud-main.yml, when run on the main branch
permissions:
  actions: read
  contents: read

jobs:
  main:
    name: Nx Cloud - Main Job
    uses: nrwl/ci/.github/workflows/nx-cloud-main.yml@v0.13.1
    with:
      main-branch-name: main
      number-of-agents: 8
      init-commands: |
        yarn nx-cloud start-ci-run --stop-agents-after="e2e-ci" --agent-count=8
      parallel-commands-on-agents: |
        yarn nx affected --target=e2e-ci --parallel=1

  agents:
    name: Nx Cloud - Agents
    uses: nrwl/ci/.github/workflows/nx-cloud-agents.yml@v0.13.1
    with:
      number-of-agents: 8
